# - include_role:
#     name: dacrystal.lxd
#   vars:
#     task: image
#     action: publish
#     args:
#       instance: instancename
#       project: projectname
#       alias: {{ instance }}
#       force: false

- name: Public image from instance - {{ args.instance }}
  command: lxc publish {{ args.instance }} {{ '--alias '+ args.alias if args.alias is defined else '' }} {{ '--force' if (args.force |default(false)) else '' }} --project {{ args.project |default("default") |quote }}
  register: result
  changed_when: result.rc == 0
  failed_when: result.rc != 0 and "already exists" not in result.stderr