# - include_role:
#     name: dacrystal.lxd
#   vars:
#     task: instance
#     action: launch
#     args:
#       instance: instancename
#       project: projectname
#       image: images:centos/8/cloud
#       profiles: []
#       vm: false
#       wait_cloud: false
#       wait_ip4: false

- name: Launch instance - {{ args.instance }}
  command: lxc launch {{ args.image }} {{ args.instance }} {%- for profile in args.profiles |default([]) %} -p {{ profile }}{% endfor %} {{ '--vm' if (args.vm |default(false)) else '' }} --project {{ args.project |default("default") |quote }}
  register: result
  changed_when: result.rc == 0
  failed_when: result.rc != 0 and "already exists" not in result.stderr

- name: Wait for cloud - {{ args.instance }}
  command: lxc exec {{ args.instance }} --project {{ args.project |default("default") |quote }} -- cloud-init status --wait
  changed_when: false
  when: args.wait_cloud |default(false)

- name: Wait for IPs - {{ args.instance }}
  shell: lxc info {{ args.instance }} --project {{ args.project |default("default") |quote }} | grep -v "lo:" | grep -w "inet" | tr '[:blank:]' ' ' | cut -d" " -f5 | grep "$^"
  retries: 120
  delay: 5
  register: result
  until: result.rc !=0
  changed_when: false
  failed_when: result.rc ==0
  when: args.wait_ip4 |default(false)
