# - include_role:
#     name: dacrystal.lxc
#   vars:
#     task: project
#     action: create
#     args:
#       project: projectname
#       description: ""
#       config:
#         features.images: "true"
#         features.profiles: "true"
#         features.storage.volumes: "true"
    
- name: Create project - {{ args.project }}
  command: lxc project create {{ args.project|quote }}
  register: result
  changed_when: result.rc == 0
  failed_when: result.rc != 0 and "already exists" not in result.stderr

- name: Edit project configurations - {{ args.project }}
  shell: |
    _get_conf='lxc project show {{ args.project|quote }}' \
    _old_conf=$($_get_conf) \
      && lxc project edit {{ args.project|quote }} << CONF \
      && diff --changed-group-format='CHANGED' --unchanged-group-format='' <(echo "$_old_conf") <($_get_conf)
    description: {{ args.description | default("") }}
    config: 
      {{ args.config | default({}) | to_yaml | indent( width=2, first=false) }}
    CONF
  args:
    executable: /bin/bash

  register: result
  changed_when: (result.rc != 0 and 'CHANGED' in result.stdout)
  failed_when: result.rc != 0 and "CHANGED" not in result.stdout